### ISSUE TITLE
Create survey questions for form implementers - USWDS Forms

### ISSUE THREAD

**Issue by jonadecker** [flexion/TTS-10x#20]
# User story
As a **10x team member**, in order to answer key questions for phase 2 such as, "What do agencies need to help implement better digital forms for the public?", I want to **create a set of interview questions to gain insights about how agencies build forms using the USWDS**.

# Acceptance criteria
- [ ] View finished, approved set of survey questions

# Tasks
- [x] Draft survey questions
- [x] Review internally with Flexion 10x team & refactor
- [x] Submit to 10x stakeholders for approval

# Definition of done
- [x] Draft survey questions in Google Forms
- [x] Socialized with Flexion 10x team members to 'vet' the structure and questions in the survey
- [x] Ready for submission to 10x

# Questions Phase 2 Should Answer
(Just a reminder, so we stay focused.)
* What, if anything, do agencies need to help implement better digital forms for
the public?
* How large is the audience?
* What are the implications for sustainability?

# Questions to consider
* Can both stakeholders and implementers be accommodated in one survey? (The interview questions are split into two separate stories.)

# References
* [Survey: USWDS - Forms Experience](https://docs.google.com/forms/d/1Tu6JAF_t_lCEaMyBF6pp-aNUyXuW-RXEoRioO3w4QTs/edit)
* [Survey: USDS - Adoption](https://docs.google.com/forms/d/1-7vMTtQL2K5-BQrusUuqqg7rZecwBu964jrOfZt0Z2k/edit)
* [USWDS Stakeholder Interview](https://docs.google.com/document/d/1M-E8RyLO3oDmaFRljyxjP_XRxZFgDIAfvvWcXt1a0wk/edit#heading=h.vknchw7niw02)
* [Digital Form Experience Pack - Phase 1 Final Recommendations](https://drive.google.com/file/d/0By82qfiUpy80YjJfT0luc21YQXB5RTE4LUdDUXBwWkxVSFQ0/view)

**Comment by ivoryhargrove** [comment]
@jonadecker a few of the questions on this survey are similar to the ones on the USWDS Adoption survey so I'm copying over those same comments. Can you make the same changes you did to address these comments on the other survey?

-is there a way to collect more specific information for "Does your team or project use USWDS?"
I'd like to know more details on why they aren't using it yet or why they're not planning to use it moving forward

-for "Were you able to easily find the guidance you needed on the USWDS site?", I'd like to know how/where they found the guidance

-for "Were you able to easily understand the information presented on the USWDS site?", it might be more beneficial for us to capture how long it took them to understand the information - with an option for "I still don't understand it"

**Comment by ivoryhargrove** [comment]
@jonadecker 

-"Have you built or converted any paper-based forms using USWDS?" and "Have you built or recreated existing web-based forms using USWDS?", if they say yes, can we give them a text box to provide additional details? I'd like to know how many

**Comment by jonadecker** [comment]
@ivoryhargrove please take a look at the Forms survey. Feel free to tweak language if desired.

**Comment by ivoryhargrove** [comment]
@jonadecker looks good! thanks for making the updates

**Comment by jonadecker** [comment]
Sent to Julia and Dan R. (cc'd @cnelsonflexion )
