### ISSUE TITLE
USWDS Adoption - Interview Questions

### ISSUE THREAD

**Issue by jonadecker** [flexion/TTS-10x#28]
# User story
As a **10x team member**, in order to answer key questions for phase 2 such as, "What have been the blockers for agencies adopting USWDS?", I want to **create a set of interview questions to gain insights about agency adoption of the USWDS**.

# Acceptance criteria
- [ ] View finished, approved interview guide

# Tasks
- [x] Draft interview guide
- [ ] Review internally with Flexion 10x team & refactor
- [ ] Submit to 10x stakeholders for approval

# Definition of done
- [ ] Draft interview guide completed in Google Docs
- [ ] Socialized with Flexion 10x team members to 'vet' the structure and questions in the interview
- [ ] Ready for submission to 10x

# References
* [Digital Form Experience Pack - Phase 1 Final Recommendations](https://docs.google.com/document/d/1YjCwJJ4FgJ7TKO4hHIaeTtWLbzcojTYjrbicdbk67wE/edit)
