### ISSUE TITLE
Create survey for USWDS Adoption

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [flexion/TTS-10x#31]
# User story
As a **10x team member**, in order to answer key questions for phase 2 such as, "What have been the blockers for agencies adopting USWDS?", I want to **create a set of survey questions to gain insights about agency adoption of the USWDS**.

# Acceptance criteria
- [ ] View finished, approved set of survey questions

# Tasks
- [x] Draft survey questions
- [x] Review internally with Flexion 10x team & refactor
- [x] Submit to 10x stakeholders for approval

# Definition of done
- [x] Draft survey questions in Google Forms
- [x] Socialized with Flexion 10x team members to 'vet' the structure and questions in the survey
- [x] Ready for submission to 10x

# Questions Phase 2 Should Answer
(Just a reminder, so we stay focused.)
* What have been the blockers for agencies adopting USWDS?
* What additional components or guidance would be the most useful?
* How large is the audience?
* What are the implications for sustainability?

# Questions to consider
* Can both stakeholders and implementers be accommodated in one survey?

# References
* [Survey: USDS - Adoption](https://docs.google.com/forms/d/1-7vMTtQL2K5-BQrusUuqqg7rZecwBu964jrOfZt0Z2k/edit)
* [Survey: USWDS - Forms Experience](https://docs.google.com/forms/d/1Tu6JAF_t_lCEaMyBF6pp-aNUyXuW-RXEoRioO3w4QTs/edit)
* [USWDS Stakeholder Interview](https://docs.google.com/document/d/1M-E8RyLO3oDmaFRljyxjP_XRxZFgDIAfvvWcXt1a0wk/edit#heading=h.vknchw7niw02)
* [Phase 1 Final Recommendations](https://docs.google.com/document/d/1YjCwJJ4FgJ7TKO4hHIaeTtWLbzcojTYjrbicdbk67wE/edit)
* [Flexion 10x Research Plan](https://docs.google.com/document/d/1wS_VuEWVWqyC2I1Xgr8vY1z0Ita5wz1isVJCOPfWRRI/edit)

**Comment by Ben-Judy-Flexion** [comment]
I took another pass at refining the questions in this survey.
I reviewed the Phase 1 Final Recommendations and the draft survey questions to inform my refinements.

Added:
* What additional components or guidance would you like to see added to the USWDS?
* In your opinion, how important is 'web sustainability' to your agency's digital work? (Sustainable web design focuses on findability, efficiency, accessibility, and optimization so that web sites save energy and reduce effort.)
* How important is the USWDS in contributing to efforts to increase sustainability?
* Please share any additional thoughts you have about the implications of the USWDS for sustainability.
* In your opinion, how capable are you and your team for contributing effectively to the USWDS?

I also made a few questions required that previously were not required in the Google Form.

**Comment by Ben-Judy-Flexion** [comment]
Ready for review: [Survey: USDS - Adoption](https://docs.google.com/forms/d/1-7vMTtQL2K5-BQrusUuqqg7rZecwBu964jrOfZt0Z2k/edit)
All, please take a look and leave a comment here with your thoughts -- done, or needs work?

**Comment by ivoryhargrove** [comment]
@Ben-Judy-Flexion I looked through the survey and had a few comments
-is there a way to collect more specific information for "Does your team or project use USWDS?" 

I'd like to know more details on why they aren't using it yet or why they're not planning to use it moving forward


- for "Were you able to easily find the guidance you needed on the USWDS site?", I'd like to know how/where they found the guidance

- for "Were you able to easily understand the information presented on the USWDS site?", it might be more beneficial for us to capture how long it took them to understand the information - with an option for "I still don't understand it"

**Comment by jonadecker** [comment]
Sent to Julia and Dan R. (cc'd @cnelsonflexion )
