### ISSUE TITLE
Identify survey audience for A11y in Visualizations

### ISSUE THREAD

**Issue by jonadecker** [flexion/TTS-10x#32]
# User story
As a **10x team member**, in order to answer key questions for phase 2 such as, "What percent of an accessibility test could be passed with smart defaults / automated feedback from a tool?", I want to **identify who will we survey to gain insights about accessibility in data visualizations**.

# Acceptance criteria
- [ ] View finished, approved list of survey participants

# Tasks
- [ ] Draft list of survey participants
- [ ] Review internally with Flexion 10x team & refactor
- [ ] Submit to 10x stakeholders for approval

# Definition of done
- [ ] Draft survey recipient list in Google Docs
- [ ] Socialized with Flexion 10x team members to 'vet' the list
- [ ] Ready for submission to 10x

# Questions Phase 2 Should Answer
(Just a reminder, so we stay focused.)
* What is the best way to recruit usability test participants with disabilities? 
* Are the Section 508 tests sufficient for data visualizations, or does there need to be usability testing to evaluate them? 
* What percent of an accessibility test could be passed with smart defaults / automated feedback from a tool? How much of that is in place for tools already? 
* How much do visualization creators need to know about accessibility to create visualizations that are accessible? How much can a tool actually do for them? 
* How interested are maintainers of various tools in improving their accessibility? 
* Is there a way to help stakeholders around data visualizations prioritize accessibility? 
* What would it take to determine that a new (USWDS) tool needs to be written from scratch?

# References
* [USWDS
Visualization Tool - Phase 1 Final Recommendations](https://drive.google.com/file/d/0By82qfiUpy80ZGhyMWlVRnF1UDRVNHdRMVB2T2VuSjV6V25B/view)
